---
title: "Santa Barbara Coastal Stream Chemistry: Agglomerative Hierarchical Clustering by Site"
author: "Genevieve Chiong"
date: "3/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(janitor)
library(NbClust)
library(cluster)
library(factoextra)
library(dendextend)
library(ggdendro)
```


```{r}
# Read in the data 
stream_chem <- read_csv(here("data", "sbc_lter_registered_stream_chemistry.csv"))

# Wrangle the data so that there is a single summary row per site (based on means from all observations at that site) and convert -999 values to NA
stream_chem[stream_chem < 0] <- NA

stream_chem_summary <- stream_chem %>% 
  group_by(site_code) %>% 
  summarize(mean_nh4 = mean(nh4_uM, na.rm = TRUE),
            mean_no3 = mean(no3_uM, na.rm = TRUE),
            mean_po4 = mean(po4_uM, na.rm = TRUE),
            mean_tdn = mean(tdn_uM, na.rm = TRUE),
            mean_tdp = mean(tdp_uM, na.rm = TRUE),
            mean_tpc = mean(tpc_uM, na.rm = TRUE),
            mean_tpn = mean(tpn_uM, na.rm = TRUE),
            mean_tpp = mean(tpp_uM, na.rm = TRUE),
            mean_tss = mean(tss_mgperLiter, na.rm = TRUE),
            mean_spec = mean(spec_cond_uSpercm, na.rm = TRUE)) 

stream_chem_summary[stream_chem_summary == "NaN"] <- NA
```


```{r}
# Drop rows where any of the chemistry measurements are missing 
stream_chem_complete <- stream_chem_summary %>% 
  drop_na(mean_nh4:mean_spec)

# Scale the numeric variables (columns 2:11)
stream_chem_complete_scaled <- stream_chem_complete %>% 
  select(2:11) %>% 
  scale()

# Update to add rownames (site code) from stream_chem_complete 
rownames(stream_chem_complete_scaled) <- stream_chem_complete$site_code
```


```{r}
# Compute dissimilarity values (Euclidean distances): 
euc_distance <- dist(stream_chem_complete_scaled, method = "euclidean")

#euc_distance

# Agglomerative hierarchical clustering (complete linkage) for water chemistry by site
hc_complete <- hclust(euc_distance,
                      method = "complete")

# Create a dendrogram showing multivariate clustering for water chemistry by site
ggdendrogram(hc_complete) +
  theme_minimal() + 
  labs(x = "\nSite",
       y = "Height\n")
```


### Citations

Citation: Santa Barbara Coastal LTER and J. Melack. 2019. SBC LTER: Land: Stream chemistry in the Santa Barbara Coastal drainage area, ongoing since 2000 ver 16. Environmental Data Initiative. https://doi.org/10.6073/pasta/67a558a24ceed9a0a5bf5e46ab841174. 




